# Generated by Django 5.2.7 on 2025-12-07 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_tag_weapons_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weapons',
            old_name='author',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='weapons',
            old_name='published_date',
            new_name='type_bullet',
        ),
        migrations.RenameField(
            model_name='weapons',
            old_name='title',
            new_name='year',
        ),
    ]
