# Generated by Django 5.2.7 on 2025-12-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_author_weapons_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Weapons',
            new_name='Weapon',
        ),
    ]
