# Generated by Django 5.2.7 on 2025-12-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_weapons_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='type_bullet',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='year',
            field=models.DateField(max_length=100),
        ),
    ]
