# Generated by Django 5.2.7 on 2025-12-07 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_alter_weapon_type_bullet_alter_weapon_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='year',
        ),
    ]
