# Generated by Django 5.2.8 on 2025-12-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_remove_weapon_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='date',
            field=models.DateField(default='2025-12-08'),
            preserve_default=False,
        ),
    ]
